# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b60c734d09b0ef0044c33b1d2ed1682c688841f038a94dbfd5eaab67ecc0fcfc38f582cc49418403a07dc04823f9e079d62bae9bc1a8ff3d22e76ff40589d519

test:
  secret_key_base: e45b6e30bc615d1ad92cff94c3c252ba86a1566bbed8b7979fb80185ce0e7d364454e36486f282af2aec90d25913c8d12d8c2a5210d254c3f8fb2a9f699f32d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
